import {createRouter,createWebHistory} from 'vue-router'

export default createRouter({
    history:createWebHistory(),
    //路由表
    routes:[
        {
            path:'/',
            redirect:'/Login'
        },
        {
            path:'/Login',
            name:'login',
            component:()=>import('../components/Login')
        },
        {
            path:'/Main',
            name:'main',
            component:()=>import('../components/Main'),
            children:[
                {
                    path:'/SaleChance',
                    name:'chance',
                    component:()=>import('../components/SaleChance')
                },{
                    path:'/EditSaleChance',
                    name:'EditSaleChance',
                    component:()=>import('../components/EditSaleChance')
                },{
                    path:'/AddSaleChance',
                    name:'AddSaleChance',
                    component:()=>import('../components/AddSaleChance')
                },{
                    path:'/SalePlan',
                    name:'plan',
                    component:()=>import('../components/SalePlan')
                },{
                    path:'/EditSalePlan',
                    name:'EditSalePlan',
                    component:()=>import('../components/EditSalePlan')
                },{
                    path:'/AddSalePlan',
                    name:'AddSalePlan',
                    component:()=>import('../components/AddSalePlan')
                },{
                    path:'/Orders',
                    name:'Orders',
                    component:()=>import('../components/Orders')
                },{
                    path:'/SysUser',
                    name:'SysUser',
                    component:()=>import('../components/SysUser')
                },{
                    path:'/EditSysUser',
                    name:'EditSysUser',
                    component:()=>import('../components/EditSysUser')
                },{
                    path:'/AddSysUser',
                    name:'AddSysUser',
                    component:()=>import('../components/AddSysUser')
                },{
                    path:'/DataArea',
                    name:'DataArea',
                    component:()=>import('../components/DataArea')
                },{
                    path:'/DataClientLevel',
                    name:'DataClientLevel',
                    component:()=>import('../components/DataClientLevel')
                },{
                    path:'/DataServerType',
                    name:'DataServerType',
                    component:()=>import('../components/DataServerType')
                }
            ]
        }
    ]
})